// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyq-peVO386pPMPXohcQyyEgl2F78DWxU',
    appId: '1:1035528335824:web:8c382a4780f1d02ab209d5',
    messagingSenderId: '1035528335824',
    projectId: 'spendi',
    authDomain: 'spendi-1a378.firebaseapp.com',
    storageBucket: 'spendi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT8Xx1mzL90aBF6TvpBmAVWwbozoAzJY0',
    appId: '1:1035528335824:android:2b119cd7026f3a33b209d5',
    messagingSenderId: '1035528335824',
    projectId: 'spendi',
    storageBucket: 'spendi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ATxuIrGul2D-wr_Mf35c6TdZx1FNMJk',
    appId: '1:1035528335824:ios:30133d793a99853ab209d5',
    messagingSenderId: '1035528335824',
    projectId: 'spendi',
    storageBucket: 'spendi.appspot.com',
    iosClientId: '1035528335824-0didi7oqoqati2mm4q6d4ng5bme4c3dg.apps.googleusercontent.com',
    iosBundleId: 'com.natashadraper.spendi',
  );
}
